//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLearningDB
{
    using Cirrious.MvvmCross.Community.Plugins.Sqlite;
    using System;
    using System.Collections.Generic;
    
    public  class quiz_by_circle : Quiz
    {
        [PrimaryKey, AutoIncrement]

        new public int id { get; set; }
        public int id_pk { get; set; }

        public int circle_id { get; set; }
        public int User_id { get; set; }      
        public float qualification { get; set; }
       
    }
}
