#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MLearning.Droid.Resource", IsApplication=true)]

namespace MLearning.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ByteSmith.WindowsAzure.Messaging.Resource.String.library_name = global::MLearning.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int button2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int imageView1 = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout3 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int listVie3 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int listView1 = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int listView2 = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int mvx_MvxListView1 = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView3 = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int textView4 = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AuthView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateAccountView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateInstitutionView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HeadMainView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_circle = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item_group_page = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_institution = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int item_lo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int item_lo_bg = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int item_lo_comment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int item_page = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int item_post = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int item_publisher = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int item_question_op = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int item_quiz = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int item_stack = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int item_user = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LoginView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LOView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int MainView = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ManageCirclesView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ManagePublishersView = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int PublisherMainView = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int RegistrationView = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int SplashScreen = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
